# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      
      - name: chmod gradle
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build --no-daemon
        
      - name: check build
        run: ls ./build/libs
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: docker ps
        run: docker ps
        
      - name: docker copy
        run: cp ./build/libs/*.war ./Dockerfile
      
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest ./Dockerfile
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_${GITHUB_RUN_ATTEMPT} ./Dockerfile

      - name: docker images
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: docer push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest
        
      - name: re-name
        run: mv ./build/libs/*.war ./build/libs/backup${GITHUB_SHA::7}.war
        
      - name: ls
        run: ls -al ./build/libs
       
      - name: GKE auth
        uses: 'google-github-actions/auth@v0'          
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
        
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v0.7.0
        with:
          cluster_name: xoxeez
          location: us-central1-c
     
      - name: was-deploy restart
        run: kubectl rollout restart deployment/was
        
      - name: GKE Cloud Storage auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_S3_TOKEN }}

      - name: upload-folder
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: ./build/libs/
          destination: backup-war/
          parent: false
